spring:
  application:
    name: eureka-consumer-ribbon-hystrix
server:
  port: 2200
eureka:
  client:
    serviceUrl:
      #defaultZone: http://eureka.didispace.com/eureka/
      defaultZone: http://localhost:8761/eureka/
